# Feature Engineering Configuration

feature_groups:
  flow_statistics:
    - "Flow Duration"
    - "Total Fwd Packets" 
    - "Total Backward Packets"
    - "Total Length of Fwd Packets"
    - "Total Length of Bwd Packets"
    - "Fwd Packet Length Max"
    - "Fwd Packet Length Min"
    - "Fwd Packet Length Mean"
    - "Fwd Packet Length Std"
    - "Bwd Packet Length Max"
    - "Bwd Packet Length Min"
    - "Bwd Packet Length Mean"
    - "Bwd Packet Length Std"

  timing_features:
    - "Flow Bytes/s"
    - "Flow Packets/s"
    - "Flow IAT Mean"
    - "Flow IAT Std"
    - "Flow IAT Max"
    - "Flow IAT Min" 
    - "Fwd IAT Total"
    - "Fwd IAT Mean"
    - "Fwd IAT Std"
    - "Fwd IAT Max"
    - "Fwd IAT Min"
    - "Bwd IAT Total"
    - "Bwd IAT Mean"
    - "Bwd IAT Std"
    - "Bwd IAT Max"
    - "Bwd IAT Min"

  behavioral_features:
    - "Fwd PSH Flags"
    - "Bwd PSH Flags"
    - "Fwd URG Flags"
    - "Bwd URG Flags"
    - "Fwd Header Length"
    - "Bwd Header Length"
    - "Fwd Packets/s"
    - "Bwd Packets/s"
    - "Min Packet Length"
    - "Max Packet Length"
    - "Packet Length Mean"
    - "Packet Length Std"
    - "Packet Length Variance"

  advanced_features:
    - "FIN Flag Count"
    - "SYN Flag Count"
    - "RST Flag Count"
    - "PSH Flag Count"
    - "ACK Flag Count"
    - "URG Flag Count"
    - "CWE Flag Count"
    - "ECE Flag Count"
    - "Down/Up Ratio"
    - "Average Packet Size"
    - "Avg Fwd Segment Size"
    - "Avg Bwd Segment Size"

sliding_window:
  enabled: true
  window_sizes: [10, 25, 50]  # Number of packets
  features:
    - "packet_size_mean"
    - "packet_size_std"
    - "iat_mean"
    - "iat_std"
    - "throughput"

feature_selection:
  method: "importance"  # Options: importance, correlation, univariate
  max_features: 50
  importance_threshold: 0.01
  correlation_threshold: 0.95
